public class ClassB {
public static Integer add(Integer num1, Integer num2) {
        Integer sum = num1 + num2;
        return sum;
    }
    
    public static Integer subtract(Integer num1, Integer num2) {
        Integer difference = num1 - num2;
        return difference;
    }
    
    public static Integer multiply(Integer num1, Integer num2) {
        Integer product = num1 * num2;
        return product;
    }
}